config/routes.rb
Inrealmoney::Application.routes.draw do
  devise_for :users
  resources :units
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get 'conversion/index' => 'conversion#index'
  get 'conversion/convert' => 'conversion#convert'
  root "conversion#index"
  

end

app/models/units.rb
class Units < ActiveRecord::Base
	belongs_to :user
	DISTANCES = [METERS = 'meters', MILES = 'miles']

	def distances_enum
		[METERS, MILES]
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :units, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversion_controller.rb
class ConversionController < ApplicationController
	before_filter :authenticate_user!
	def index
	end
	def convert
		input_value = params['input_value']
		input_unit = Unit.new(input_value)
		p(current_user)
		p  "Converting------------------------------------------------------------"
		converted_unit = input_unit >> current_user.units.distance
        #p "Converting------------------------------------------------------------"
        converted_unit=converted_unit.to_s("%0.2f")
		p converted_unit
        respond_to do |format|
	        format.json { render :json => {"conversion_value" => converted_unit}}
	    end
	end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
	def show
		redirect_to "/"
	end

	def update
		@units = Units.find(params[:id])
		if @units.update(units_params)
		redirect_to "/"
	else
		render 'edit'
	end
end

	def edit
	@units=Units.find params[:id]
	end

	def units_params
		params.require(:units).permit(:distance,:speed,:currency)

	end
	DISTANCES = [METERS = 'meters', MILES = 'miles']

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversion_helper.rb
module ConversionHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/conversion/index.html.erb
<div class= "center hero-unit">
<!--<h1>Welcome to inrealmoney.com</h1>-->
<p>"Show Me the Money"</p>
<%= text_field(:conversion_field, :name, id: "conversion_field")%>
<div id="conversion_output">
</div>

<% current_user.units.attributes.each do | unit_name, unit_value | %>
	<% not_wanted = %w(id created_at updated_at sign_in_count user_id) %>
		<%if ! not_wanted.include? unit_name  %>
			<span class="label label-success"> <%= unit_name.to_s + ": " + unit_value.to_s %></span>
	<% end %>
<% end %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
#<script src='https://www.google.com/jsapi'></script>
<title>inrealmoney</title>
<%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= javascript_include_tag :defaults, 'nested_form' %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
    <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
            <div class="container">
                <%= link_to "inrealmoney", '#', id: "logo" %>
                <nav>
                    <ul class="nav pull-right">
                        <li><%= link_to "Home",    '/' %></li>
                        <% if user_signed_in? %>
                            <li><%= link_to current_user.email,
                              root_path+'profiles/'+"empty string"
                                %></li>
                                <li><%= link_to "Edit Units", edit_unit_path(current_user.units) %></li>
                                <li><%= link_to "Sign out", "/users/sign_out", 
                                    :method => :delete %></li>
                        </a>
                        
                        </li>
                    <% else %>
                            <li><%= link_to "Sign In", "/users/sign_in" %></li>
                            <li><%= link_to "Sign Up", "/users/sign_up" %></li>
                    <% end %>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div class="container">
        <%= yield %>
    </div>
    </body>
    </html>

app/views/units/edit.html.erb
You are now editing your unit preferences
<div class="center hero-unit">
            <%= simple_form_for(@units, html: {class: 'form-horizontal' }) do |f| %>
            <%= f.input :distance, as: :select, collection: {:Miles => 'miles',:Meters => 'meters',:Feet => 'feet'} %>
            <%= f.input :speed %>
            <%= f.input :currency %>
            <%= f.button :submit %>
        <%end%>
	</div>